### ISSUE TITLE
How many pictures you are using for training?

### ISSUE THREAD

**Issue by lyyiangang** [swook/GazeML#13]
Hi sir.
I see your gaze demo on youtube, it's amazing. I download you pre-trained model and test on my own videos, but don't get good results. my questions are:
1. How many pictures are used for your pre-trained model? 
2. which gaze method is used in your video demo? feature based method or model based method? 

thanks very much

**Comment by swook** [comment]
Hi, thanks for the kind comments.

1. I believe I used almost a million images for training.
2. The video uses a feature-based (SVR) method trained on MPIIGaze - if I remember correctly. The reference implementation in this repository does not do this and relies on the somewhat inaccurate estimation of eyeball center and radius.

**Comment by lyyiangang** [comment]
> Hi, thanks for the kind comments.
> 
> 1. I believe I used almost a million images for training.
> 2. The video uses a feature-based (SVR) method trained on MPIIGaze - if I remember correctly. The reference implementation in this repository does not do this and relies on the somewhat inaccurate estimation of eyeball center and radius.

thanks very much for your reply. it seems I need generate more pictures for training.
Thanks very much.

**Comment by XhqGlorry11** [comment]
@swook Hi, according to the checkpoint you provide, do you train the model for more than 4 million steps? Assuming your batch size is 32, that means your model have seen more than 120 million images???

**Comment by swook** [comment]
Hi, this may indeed be the case. The landmarks model takes a lot of data
and time to train.

**Comment by Alion118** [comment]
> Hi, thanks for the kind comments.
> 
> 1. I believe I used almost a million images for training.
> 2. The video uses a feature-based (SVR) method trained on MPIIGaze - if I remember correctly. The reference implementation in this repository does not do this and relies on the somewhat inaccurate estimation of eyeball center and radius.

-----------------------------------------------------------------------------------------------------
Hi, I got a question that it's a million images before Training Data Augmentation or after augmentation ? And I use UnityEyes to generate almost 140 thousand images,  it's up to 1 million after augmentation. Then I run the egg_train.py and got this problem:

-----------------------------------------------------------------------------------------------------
10/04 06:34 INFO 0079261> heatmaps_mse = 0.00100194, radius_mse = 1.17517e-07
10/04 06:34 INFO 0079270> heatmaps_mse = 0.00119301, radius_mse = 8.82096e-08
10/04 06:34 INFO 0079280> heatmaps_mse = 0.00114937, radius_mse = 1.55061e-07
10/04 06:34 INFO 0079289> heatmaps_mse = 0.00109943, radius_mse = 1.84821e-07
Exception in thread preprocess_UnityEyes_27:
Traceback (most recent call last):
  File "/home/wang/anaconda3/envs/tensorflow-gpu/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/wang/anaconda3/envs/tensorflow-gpu/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/media/wang/Toshiba/lmj/2019term/papers/GazeML/GazeML-win/src/core/data_source.py", line 245, in preprocess_job
    preprocessed_entry_dict = self.preprocess_entry(raw_entry)
  File "/media/wang/Toshiba/lmj/2019term/papers/GazeML/GazeML-win/src/datasources/unityeyes.py", line 237, in preprocess_entry
    thickness=int(6*line_rand_nums[j + 4]), lineType=cv.LINE_AA)
cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/drawing.cpp:1811: error: (-215:Assertion failed) 0 < thickness && thickness <= MAX_THICKNESS in function 'line'

**Comment by swook** [comment]
I used approx. 1 million images before augmentation. The augmentation scheme is live during the training of the model and thus results in an effectively uncountable training set.

Please open a separate issue for the error you ran into.

**Comment by TulipDi** [comment]
> 1. I believe I used almost a million images for training.
> 2. The video uses a feature-based (SVR) method trained on MPIIGaze - if I remember correctly. The reference implementation in this repository does not do this and relies on the somewhat inaccurate estimation of eyeball center and radius.

Hi, i have a question that how train SVR on MPIIGaze. I get MPIIGaze by 'get_mpiigaze_hdf.bash '. Then I found this dataset does not have 'landmark'.  Wait for your reply!
