### ISSUE TITLE
Ouput raw data points from model prediction

### ISSUE THREAD

**Issue by saadali1996** [swook/GazeML#15]
I would like a bit of clarification, is it possible to output like head pose value, eye gaze position data from the model in debug mode or log it. And how to use it for single image prediction rather than video or webcam feed. Your help would be highly appreciated.

**Comment by swook** [comment]
Hi, apologies for the late response. It is not possible to output head pose
as this is not estimated in the code base. While there is no way of doing
single image inference, one could implement this by implementing a custom
data source class and main script.

**Comment by saadali1996** [comment]
Got it. Thanks a lot for your response.
