### ISSUE TITLE
Directly regressing gaze angles from unity_eyes data?

### ISSUE THREAD

**Issue by XhqGlorry11** [swook/GazeML#16]
Hi @swook, nice work and congrats! I notice that gaze direction ground truth info is also generated in unity_eyes data. I am wondering why not modify the network structure a little bit and directly regressing gaze angles based on landmark using unity_eyes dataset's gaze ground truth info as supervision? Why train a SVM on MPIIGaze dataset seperately?  Have I missed something?
Thank U! ^ ^

**Comment by swook** [comment]
Hello, thank you for the kind words.

In my research I attempted to directly learn to regress gaze from the
landmarks in an end-to-end fashion but was unable to yield good results.
Perhaps though, I was missing something in my implementation - so I would
not necessarily like to discourage you from exploring this possibility.

**Comment by XhqGlorry11** [comment]
@Hi, thanks for your IMMEDIATELY reply!! So you are mainly interested in learning gaze estimation from landmark end2end and didn't try the schedule I mentioned above?

**Comment by swook** [comment]
If I did not misunderstand, you were describing exactly end-to-end gaze
estimation with intermediate landmark estimation, from UnityEyes and yes, I
tried this before.

**Comment by XhqGlorry11** [comment]
@swook , how does that pipeline work? Can you share some results?

**Comment by swook** [comment]
I do not have any results from those experiments anymore, sorry about that.
