### ISSUE TITLE
how to compare result against UT multi view gaze dataset? 

### ISSUE THREAD

**Issue by lyyiangang** [swook/GazeML#20]
Hi Sir,
I am trying to train your net against UT multi-view dataset.  I am facing a problem about the converting of gaze vector to yaw and pitch angle .
In the dataset, s00/test/000_left.csv contain following lines:
```0.657246  0.0937712  -0.74782  -0.0511348  -0.548227  -0.0143822  -7.6967E-06  1.92417E-06  600```
the first 3 numbers '0.657246 0.0937712 -0.74782' is gaze direction in camera coordinate, I convert it to yaw and pitch directly like this:
```
   # gaze direction (gx, gy, gz)
    yaw = np.arctan2(-gx, -gz)
    pitch = np.arcsin(-gy)
```
But it seems not correct after I plot the gaze vector to original image. Could you give some tips or code?

Thanks very much.

**Comment by swook** [comment]
Hi sorry for the late response.

How are you visualizing gaze direction? Is it with the `draw_gaze` method in https://github.com/swook/GazeML/blob/master/src/util/gaze.py#L102

If so, perhaps you should use the `vector_to_pitchyaw` method implemented there.

**Comment by lyyiangang** [comment]
@swook I am sure the problem is about the parsing and converting of UT multi-view dataset, do you have the parsing code about this dataset? thanks.

**Comment by swook** [comment]
How do you determine that the results "seems not correct"?

I have not processed the UT Multiview dataset myself before and thus have no code, sorry about that.

**Comment by lyyiangang** [comment]
Thanks, the structure of UT Multiview dataset is a little complicated. they use too many coordinates. thanks for your help.
