### ISSUE TITLE
error occurs when i run elg.py

### ISSUE THREAD

**Issue by TulipDi** [swook/GazeML#26]
OS: ubuntu 18.04
Python: 3.6.7
Tensorflow: 1.12.0
opencv: 4.0.0

Thanks for your work! When I run the elg_train.py,  it works perfect util step (about) 075000.
when i meet this error, sometimes, it can work continue or just stop after work 4-6 steps. Looking forward to your reply.
`
10/05 16:14 INFO 0083137> heatmaps_mse = 0.00106249, radius_mse = 1.75501e-07
10/05 16:15 INFO 0083139> heatmaps_mse = 0.00100996, radius_mse = 1.32564e-07
Exception in thread preprocess_UnityEyes_4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vision_rd/huhuaidi/project/GazeML/src/core/data_source.py", line 245, in preprocess_job
    preprocessed_entry_dict = self.preprocess_entry(raw_entry)
  File "/home/vision_rd/huhuaidi/project/GazeML/src/datasources/unityeyes.py", line 238, in preprocess_entry
    thickness=int(6*line_rand_nums[j + 4]), lineType=cv.LINE_AA)
cv2.error: OpenCV(4.0.0) /io/opencv/modules/imgproc/src/drawing.cpp:1811: error: (-215:Assertion failed) 0 < thickness && thickness <= MAX_THICKNESS in function 'line'

10/05 16:15 INFO 0083141> heatmaps_mse = 0.00116619, radius_mse = 1.57683e-07
10/05 16:15 INFO 0083143> heatmaps_mse = 0.000970301, radius_mse = 1.92502e-07
10/05 16:15 INFO 0083145> heatmaps_mse = 0.00101215, radius_mse = 1.51191e-07
`

**Comment by swook** [comment]
Hi could you check if the issue still exists with branch `cvlineaug_fix` (https://github.com/swook/GazeML/tree/cvlineaug_fix)?

Thanks!

**Comment by TulipDi** [comment]
> Hi could you check if the issue still exists with branch `cvlineaug_fix` (https://github.com/swook/GazeML/tree/cvlineaug_fix)?
> 
> Thanks!

**Comment by TulipDi** [comment]
> Hi could you check if the issue still exists with branch `cvlineaug_fix` (https://github.com/swook/GazeML/tree/cvlineaug_fix)?
> 
> Thanks!

Thanks for reply ! I print the value of 6*line_rand_nums[j + 4]。When value < 1, it reports an error。I just change the unityeyes.py（lines 237)
`
t = int(6*line_rand_nums[j + 4])
if t < 1 :
    t = 1
eye = cv.line(eye, (lx0, ly0), (lx1, ly1),
                              color=(line_colour, line_colour, line_colour),
                              thicknesss = t, lineType = cv.LINE_AA)
`
Then, it can work without error.  Apparently, your code is more pithy .
