### ISSUE TITLE
Aborted(core dumped)

### ISSUE THREAD

**Issue by Liumihan** [swook/GazeML#46]
Greate job! I got some errors when I run the elg_demo.py.

Traceback (most recent call last):
  File "elg_demo.py", line 69, in <module>
    eye_image_shape=(36, 60))
  File "/home/mihan/Desktop/GazeML-master/src/datasources/webcam.py", line 21, in __init__
    super().__init__(**kwargs)
  File "/home/mihan/Desktop/GazeML-master/src/datasources/frames.py", line 47, in __init__
    shuffle=False, staging=staging, **kwargs)
  File "/home/mihan/Desktop/GazeML-master/src/core/data_source.py", line 59, in __init__
    labels, dtypes, shapes = self._determine_dtypes_and_shapes()
  File "/home/mihan/Desktop/GazeML-master/src/core/data_source.py", line 194, in _determine_dtypes_and_shapes
    raw_entry = next(self.entry_generator(yield_just_one=True))
  File "/home/mihan/Desktop/GazeML-master/src/datasources/frames.py", line 106, in entry_generator
    self.detect_landmarks(frame)
  File "/home/mihan/Desktop/GazeML-master/src/datasources/frames.py", line 171, in detect_landmarks
    predictor = get_landmarks_predictor()
  File "/home/mihan/Desktop/GazeML-master/src/datasources/frames.py", line 371, in get_landmarks_predictor
    _landmarks_predictor = dlib.shape_predictor(dat_path)
RuntimeError: Error deserializing object of type int
FATAL: exception not rethrown
Aborted (core dumped)

And the enviroment is:
OS: Ubuntu 16.04
GPU: GTX 1060
CPU: Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz

_libgcc_mutex             0.1                        
absl-py                   0.8.0                  
astor                     0.8.0                  
ca-certificates           2019.5.15            
certifi                   2018.8.24             
coloredlogs               10.0                
dlib                      19.17.0                
gast                      0.2.2                 
google-pasta              0.1.7               
grpcio                    1.23.0                    
h5py                      2.9.0                     
humanfriendly             4.18                    
Keras-Applications        1.0.8                   
Keras-Preprocessing       1.1.0                     
libedit                   3.1.20181209      
libffi                    3.2.1            
libgcc-ng                 9.1.0               
libstdcxx-ng              9.1.0          
Markdown                  3.1.1             
ncurses                   6.1
numpy                     1.17.1                 
opencv-python             4.1.0.25            
openssl                   1.0.2s          
pandas                    0.25.1              
pip                       10.0.1       
pip                       19.2.3                   
protobuf                  3.9.1                    
python                    3.5.6           
python-dateutil           2.8.0           
pytz                      2019.2        
readline                  7.0               
scipy                     1.3.1                    
setuptools                41.2.0                  
setuptools                40.2.0               
six                       1.12.0                 
sqlite                    3.29.0              
tensorboard               1.14.0               
tensorflow-estimator      1.14.0rc1          
tensorflow-gpu            1.14.0                
termcolor                 1.1.0                 
tk                        8.6.8                
ujson                     1.35                     
Werkzeug                  0.15.5                
wheel                     0.31.1                   
wrapt                     1.11.1                  
xz                        5.2.4              
zlib                      1.2.11

**Comment by Dayire** [comment]
Same issue, any solution?

**Comment by ShukuiZhang** [comment]
Have similar issue before, in my case, it turns out that the two `.dat` file in `GazeML/src/3rdparty/` are with 0 bytes.  Issue resolved by re-downloading the counterpart from `https://github.com/davisking/dlib-models`.
