### ISSUE TITLE
Where the value of original_eyeball_radius comes from ?

### ISSUE THREAD

**Issue by tuanphuc** [swook/GazeML#5]
Hi, first I want to thank you for your great project.

I have one question regarding the value of `original_eyeball_radius = 71.7593`, how can you get this value ? Is it in the parameters of UnityEye ?

Thanks

**Comment by swook** [comment]
To find this figure, I performed my model-fitting approach on a large number of UnityEyes images with varying eyeball radius values. I then essentially took an `argmax` to find the eyeball radius which yielded the minimal model-based gaze estimation error.

You can refer to https://goo.gl/ZnXgDE to find numbers from my experiments. (Also mentioned in https://github.com/swook/GazeML/blob/master/src/datasources/unityeyes.py#L193)

Hope this helps.

**Comment by tuanphuc** [comment]
Ah I missed that comment. Thanks
