### ISSUE TITLE
Fail to run demo on CPU

### ISSUE THREAD

**Issue by hoangcuongbk80** [swook/GazeML#63]
Hi,

Thanks for sharing you work!
@swook  Could you give a suggestion about this error?

![1](https://user-images.githubusercontent.com/10355081/77246193-0f081880-6c25-11ea-9441-6cbb934ee299.png)

I am using Tensorflow 1.11.0 CPU

**Comment by 0xsuu** [comment]
It is a dlib error, I resolved the issue by replacing the `shape_predictor_5_face_landmarks.dat` file under 3rdparty with [https://github.com/davisking/dlib-models/blob/master/shape_predictor_5_face_landmarks.dat.bz2](https://github.com/davisking/dlib-models/blob/master/shape_predictor_5_face_landmarks.dat.bz2).

**Comment by hoangcuongbk80** [comment]
It works! Thank you!
