### ISSUE TITLE
gaze inference 

### ISSUE THREAD

**Issue by liuhaiyang2018** [swook/GazeML#7]
How to load the model separately for gaze inference?

**Comment by swook** [comment]
Hi, please see https://github.com/swook/GazeML/blob/master/src/elg_demo.py and https://github.com/swook/GazeML/blob/master/src/core/model.py#L275 for a somewhat complex example...

**Comment by swook** [comment]
Please refer to the code at https://github.com/swook/GazeML/blob/master/src/util/gaze.py#L45

Best wishes,
Seonwook
