### ISSUE TITLE
Heatmaps values are exceptionally low- unable to generate gaze

### ISSUE THREAD

**Issue by patilsvaibhav** [swook/GazeML#8]
Hello,

I've been trying to get this code to run for some time now. When I do, i can only see two red dots at corner of eyes, and no gaze vector or iris landmarks as in the video.

I digged deeper and the issue apparently is in the values of heatmaps. 
This is how it looks:
HeatMaps_amax: [0.04515158 0.07932845 0.05255887 0.06401039 0.02747708 0.0497707
 0.06598783 0.04077904 0.03464168 0.00753675 0.01112193 0.00911523
 0.03209448 0.03100399 0.0287441  0.02697178 0.03532294 0.05629761]

None of them are even close to 0.1, and the key conditions require them to atleast greater than 0.7.
So the estimation code block never gets executed.

I have downloaded the model files from the BASH script and kept both folders under output directory.
Still there is no improvement in the values.

Can you please suggest what could be the issue here.
TIA
Vaibhav

**Comment by swook** [comment]
This is most definitely due to the pre-trained weights not being loaded before inference. Please ensure that the model files are in the correct location (run the script using bash) and check that the console output indicates the loading of the available weights.

**Comment by patilsvaibhav** [comment]
Thanks swook, that worked!
I'm running a windows system so manually extracted the zip files. The folder structure was indeed incorrect. Its working perfectly now.

I have one more issue where I'm stuck. 
Now my question is, how to estimate the gaze point on the screen that user is looking at. Below is some more information that I have:

1. Camera is located on top of screen (just like in case of webcam and laptop)
2. Person is not at any standard distance from the camera

also please note that I don't want to calibrate at fixed points on screen. Because it would again need human intervention

I was thinking of finding the intersection point of the gaze vector with the plane of camera. This seems doable mathematically. However, I'm not able to find how to define the plane of the Camera.

Could you please direct me in the right direction? 

Appreciate your help.

Regards,
Vaibhav

**Comment by swook** [comment]
I'm sorry but it's not most ideal to be poked at 2 different github issues and one e-mail, regarding the exact same question, presumably from you and your colleague. I will address this in #9.

**Comment by patilsvaibhav** [comment]
Hi Seonwook,

Sorry about the duplication.
He is indeed my colleague(copied in this email), and we posted to you
independently, unaware of  each other's questions.

Nevertheless, we want to thank you for all the guidance you have been
giving and really appreciate your active presence on the forum.

We will keep you posted on the progress and hopefully a solution.

Thanks,
Vaibhav

**Comment by swook** [comment]
No worries, it happens :smile:

**Comment by keishatsai** [comment]
> Thanks swook, that worked!
> I'm running a windows system so manually extracted the zip files. The folder structure was indeed incorrect. Its working perfectly now.
> 
> I have one more issue where I'm stuck.
> Now my question is, how to estimate the gaze point on the screen that user is looking at. Below is some more information that I have:
> 
> 1. Camera is located on top of screen (just like in case of webcam and laptop)
> 2. Person is not at any standard distance from the camera
> 
> also please note that I don't want to calibrate at fixed points on screen. Because it would again need human intervention
> 
> I was thinking of finding the intersection point of the gaze vector with the plane of camera. This seems doable mathematically. However, I'm not able to find how to define the plane of the Camera.
> 
> Could you please direct me in the right direction?
> 
> Appreciate your help.
> 
> Regards,
> Vaibhav

Hi, 
I wonder that what is the correct structure folders of pre-trained weight.
Currently, I put it inside output folder:

> D:\GazeML\outputs\ELG_i60x36_f60x36_n32_m2\checkpoints\
>  D:\GazeML\outputs\ELG_i90x108_f30x36_n64_m3\checkpoints\
>  D:\GazeML\outputs\ELG_i180x108_f60x36_n64_m3\checkpoints\

**Comment by liuyantingyvonne** [comment]
> Hello,
> 
> I've been trying to get this code to run for some time now. When I do, i can only see two red dots at corner of eyes, and no gaze vector or iris landmarks as in the video.
> 
> I digged deeper and the issue apparently is in the values of heatmaps.
> This is how it looks:
> HeatMaps_amax: [0.04515158 0.07932845 0.05255887 0.06401039 0.02747708 0.0497707
> 0.06598783 0.04077904 0.03464168 0.00753675 0.01112193 0.00911523
> 0.03209448 0.03100399 0.0287441 0.02697178 0.03532294 0.05629761]
> 
> None of them are even close to 0.1, and the key conditions require them to atleast greater than 0.7.
> So the estimation code block never gets executed.
> 
> I have downloaded the model files from the BASH script and kept both folders under output directory.
> Still there is no improvement in the values.
> 
> Can you please suggest what could be the issue here.
> TIA
> Vaibhav

Hello, Could you please tell me where the pre-training weight should be placed in the Windows system?
