### ISSUE TITLE
Can not get pre-trained weights

### ISSUE THREAD

**Issue by foreeest** [swook/GazeML#93]
When I input '' bash get_trained_weights.bash '' 
I get ''https://ait.ethz.ch/projects/2018/landmarks-gaze/downloads/ELG_i180x108_f60x36_n64_m3.zip:
2024-05-01 00:46:55 ERROR 404: Not Found.
unzip:  cannot find or open ELG_i180x108_f60x36_n64_m3.zip, ELG_i180x108_f60x36_n64_m3.zip.zip or ELG_i180x108_f60x36_n64_m3.zip.ZIP.''  

It seems that the url doesn't work

**Comment by Mikinox3** [comment]
Hi @foreeest ! Did you find a way to get the files ?

**Comment by foreeest** [comment]
@Mikinox3 I didn't find it, but there is a [unofficial implementation](https://github.com/shaoanlu/GazeML-keras) with their pre-trained weights

**Comment by swook** [comment]
Apologies for the broken links. They are now fixed (27f4e780c6720bf10735dc08597af9d895f14491)
